# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "monthly"
    groups:
       remix-deps:
          patterns:
            - "@remix-run/*"
            - "@vercel/remix"
       react:
          patterns:
            - "react"
            - "react-dom"
            - "@types/react-dom"
            - "@types/react"
